//RUMENUFF


//updated 29.12.25




//word and question array are in rows of 10.
// answers must be in all capitals due to key reading
var wordarray = ["SNOWIE", "EMBOSS", "PASTEURISED", "CANOODLE", "UNBIASSED", "CASTAWAY", "CHASTE", "RUMINANT", "DISCUS", "PESTICIDE",
    "LEMONADE", "PLATONIC", "ACUPUNCTURE", "MILKSHAKE", "HYPERBOLE", "RASHER", "TOURNIQUET", "PUNT", "STAGECOACH", "LEGENDS",
    "POPCORN", "MALADY", "VANGUARD", "ICICLE", "NEVERTHELESS", "COLLAGE", "EASEL", "KIMONO", "LAMB", "FANFARE",
    "UMPIRE", "REPERCUSSION", "DIVERSE", "CAHOOT", "DELAY", "CONTRABAND", "AISLE", "HOOPLA", "LETTUCE", "EXTINCT",
    "SOMBRERO", "BELITTLE", "STOREY", "TOTEM", "CHAMPIGNON", "FURNACE", "RACKETEER", "JOURNEYMAN", "DEADPAN", "WINSOME",
    "BLOUSE", "PALAVER", "QUOTA", "FLUMMOXED", "CASHEW", "ACCENTUATE", "MANDARIN", "FUTILITY", "UNABASHED", "LENS",
    "CANTALOUPE", "DICTIONARY", "OXYMORON", "ABOMINABLE", "SERENDIPITY", "CAROUSEL", "SEAR", "BITTEN", "BOUNDLESS", "SECRETE",
    "DIATRIBE", "SOURDOUGH", "PASSPORT", "LOCOMOTIVE", "REVELATIONS", "TIMPANI", "STATUTE", "PASSIONFRUIT", "CHAGRIN", "ZENITH",
    "ABSOLUTE", "NEIGHBOURS", "DOGMATIC", "ENDOSCOPE", "QUARTERMASTER", "CLAPTRAP", "PIANOLA", "BALCONY", "BLITHE", "SUBTLE",
    "GNUS", "SAGACITY", "BOUGH", "MACHINATIONS", "FORBID", "CUFFLINKS", "SAPLING", "DANDELION", "TANNERY", "MASCARPONE",
    "IRONY", "OVERHEADS", "DEPORT", "PORTENT", "EXHALE", "CELERY", "MOHAIR", "DERISION", "EFFLUENT", "PETULANCE",
    "CONSERVATION", "CANASTA", "ALCOVE", "BARGAINS", "BILLET", "LAYABOUTS", "REVENUE", "ULTRAMARINE", "HAMLET", "SCOWL",
    "AUDITORIUM", "MINESWEEPER", "ETHER", "PAWNBROKER", "PUNGENT", "PALLID", "LIVERWURST", "PLATFORMS", "ROOKIE", "HANDSOME",
    "DEBONAIR", "DIPLOMAT", "INSOFAR", "OPTICIAN", "REGALIA", "STAGNATION", "BARISTA", "RELATIONSHIP", "PUPPET", "BATON",
    "STAIRWELL", "DIGIT", "FLAGON", "ALLOWED", "LIQUORICE", "MASSIVE", "PESSIMIST", "BANDICOOT", "AKIMBO", "MICROWAVE",
    "FOUNDRY", "EQUIPPED", "COMMODORE", "LIEU", "DISILLUSION", "TORQUE", "PAUNCH", "IDLER", "HYDROFOIL", "BOVINE",
    "MUNCHKIN", "MEANTIME", "PEERAGE", "PREAMBLE", "INSECT", "HANDMEDOWNS", "HOVERCRAFT", "ABJECT", "DOGGEREL", "JETTISON",
    "KETCH", "CONCERTINA", "PALINDROME", "MASK", "DEARTH", "ECLIPSE", "UNICORN", "MAUDLIN", "FOOTLOOSE", "LIKEWISE",
    "PARALLELS", "INDENTURED", "MIGHTIEST", "ARTLESS", "THRONGS", "RAMIFICATIONS", "ATOLL", "EDIFICE", "CARP", "ARTEFACTS",
    "HUMDRUM", "PERUSE", "ABUNDANCE", "RETROGRADE",
    "MEATLOAF", "BARTENDER", "CASTOFFS", "RHUBARB", "ARBORIST", "GRASSHOPPER", "FEARSOME", "BRANDISH", "CARBONCOPY", "GATE",
    "ANTIDOTE", "MUSTY", "PAJAMAS", "TIMEPIECE", "SPOKESPERSON", "FERRETS", "AMENITIES", "PENULTIMATE", "RESTITUTION", "NIGHTINGALE",
    "RATIFY", "PASSE", "PIECEMEAL", "WELLWISHER", "BALLISTIC", "EXTRACTIONS", "RATTLED", "FATHOM", "FORBID", "SAMPAN",
    "INHIBITION", "DOUGHNUTS", "BACKSLIDER", "AVERSION", "ASSET", "MICROCHIPS", "HARRY", "FOOTNOTES", "OPTIMIST", "ESTIMATE",
    "IRIS", "WRISTWATCH", "COWARDICE", "PRIVATIONS", "WISHBONE", "PULSATING", "PLUSFOURS", "CARNIVORE", "COMPOSITE", "BAROQUE",
    "ADVICE", "LISTLESS", "LEMMINGS", "LICHEN", "HEARSAY", "CARTON", "SPEAKEASY", "CARDIOLOGIST", "FOOLPROOF", "CALIBRATE",
    "GRIZZLED", "MOTIONLESS", "RADIOACTIVE", "VAMOOSE", "CLOCKWISE", "COLLUSION", "EYEFUL", "INSTRUMENTS", "AFTERMATH", "GUSHER",
    "HAPHAZARD", "BIRTHRIGHT", "HEARTBURN", "IMMATERIAL", "SHUCKS", "JOINERY", "COPOUT", "ROTUNDA", "FREEFORALL", "DUNGAREES",
    "CONDESCENDING", "DEBUNK", "CURSOR", "CARNATION", "FOLLY", "FALSETTO", "FLEETING", "AFTERTHOUGHT", "RUNAROUND", "TREADMILL",
    "BARCODE", "ESCARGOT", "DISSEMBLE", "EARTHBOUND", "DECIDUOUS", "GARBAGE", "SWANSONG", "KINSHIP",
    "ONLOOKERS", "ROLLINGSTONE", "SUPERVISION", "SANDALWOOD", "AMENDMENTS", "PHIAL", "TINKERS", "UNBECOMING", "LIFECYCLE", "DOWNRIGHT", "OVERTURE", "ESCAPOLOGIST", "WELLBEING", "WATERCOLOUR", "WOEBEGONE", "INSET", "REPARTEE", "FROMAGE", "MENULOG", "SKULLDUGGERY", "RYE", "MUDFLATS", "PANACHE", "POUND", "FLUNG", "HEADSTRONG", "CARDBOARD", "SEESAW", "JUGGERNAUT", "AIRWAVES", "RATIONAL", "DERANGED", "PAUCITY", "CLOCKWORK", "WILLOTHEWISP", "SCRUMHALF", "CAMERADERIE", "RULERS", "WHIMSICAL", "LANCERS", "WOOLSHED", "SKYLARKING", "CANAPE", "STEERAGE", "CANCAN", "HOPSCOTCH", "FANCYFREE", "MOUTHPIECE", "KAYAK", "BROOMSTRUCK", "WISHYWASHY", "GLOSSARY", "COMMONPLACE", "WORDY", "SHOGUN", "CRUSTACEAN", "MADCAP", "FLAGRANT", "BEATLES", "CROCKPOT", "SANDBLAST", "BLOODHOUNDS", "FORMIDABLE", "POMPOMS", "CELLPHONE", "WARHEADS", "SEDIMENTARY", "CROCHETY", "NEGATIVITY", "TRILLIONS", "TASTEBUDS", "OVERLOOKING", "BROGUES", "SUBPLOTS", "COWHIDE", "ASTERISK", "LOOKALIKE", "SPELLBINDING", "DIMWIT", "DRONE", "BARNDANCE", "SHINDIG", "THUNDERCLAP", "CURDLE", "PIEEYED", "FACTOTUM", "BOOKSHELVER", "QUEENSLANDER", "EMULATE", "EXTENSION", "WHIRLIGIG", "DIAGNOSE", "UMTEENTH", "COMEUPPANCE", "NUMBSKULL", "THINGAMAJIG", "MOSCATO", "MINUSCULE", "MELANCHOLY", "CORGIANDBESS",
"ANTELOPE",         "MERCENARIES",         "BOOBOOS",         "ATTORNEY",         "BODYGUARD",         "COWSLIP",         "SCREENPLAY",         "SUBDIVISION",         "WHOLEHEARTED",         "FOOTRACE",         "SUITABILITY",         "TRAILBLAZER",         "GUMPTION",         "DAMNATION",         "BOOMTOWN",         "OMBUDSMAN",         "HISTRIONICS",         "KERNEL",         "SUPPOSITION",         "CONVERTIBLE",         "LAUGHINGSTOCK",         "SANDBLAST",         "MASTHEAD",         "WISTERIA",         "FOURFLUSHER",         "OPOSSUM",         "DEMOUNTABLE",         "CHAINMAIL",         "LAMBASTED",         "BUFFETING",         "POLARISED",         "FORCEFUL",         "DEADBEAT",         "DOWNCAST",         "LOUDHAILER",         "FAHRENHEIT",         "FLOPPY",         "MICROMANAGER",         "UPHOLSTERY",         "PLAYFULNESS",         "UNABIDING",         "ERASURE",         "PENINSULAR",         "BUBBLING",         "BOILOVER",         "FATIGUED",         "CARPORT",         "VENTURESOME",         "LOGGERHEADS",         "BOOKENDS",         "SEXTET",         "GREENGROCER",         "GROOVY",         "PRESENTABLE",         "ADDLED",         "CRITERIA",         "GROUNDHOG",         "UNCONVENTIONAL",         "PONDER",         "ROLLERCOASTER",         "DISCOUNTS",         "LAIR",         "MOTORMOUTH",         "INDISPUTABLE",         "GIMME",         "HILLBILLY",         "EYEBALL",         "SHOCKJOCKS",         "HINDSIGHT",         "LOOKALIKE",         "STAMPDUTIES",         "TANGO",         "RIDDANCE",         "ELABORATE",         "STOPWATCH",         "STUPENDOUS",         "SCAR",         "PENNYPINCHER",         "COUP",         "CROWDPLEASER",         "TAPDANCERS",         "RUBBISHED",         "TROTTERS",         "PANDEMONIUM",         "FATHEADED",         "DAPPLED",         "PERPETUAL",         "TUBERS",         "UNTHINKABLE",         "ROUSEABOUT",         "SPACECADET",         "DIAGNOSIS",         "FLATTERY",         "FRITTER",         "WITHER",         "INFRADIG",         "PERCOLATOR",         "SUPERCILIOUS",         "ACCUMULATION",         "PARENTHESIS", 
"TUNNELBALL",         "CAPERBERRIES",         "MEADOWLARK",         "GLADHANDER",         "CHITCHAT",         "UNASSAILABLE",         "COPIOUS",         "INVOICE",         "INFORM",         "OVERACTING",         "BOOHOOING",         "SMIDGIN",         "CHATTERBOX",         "GAINSAY",         "JADED",         "BACKCHAT",         "DACHSHUND",         "INSTALLED",         "ILLUMINATING",         "RAUNCH",         "CHLOROFORM",         "FUNFAIR",         "CASESTUDY",         "PUGNACIOUS",         "WILDERNESS",         "ILLUSIONARY",         "BAMBOOZLE",         "HEIRLOOM",         "MAJESTIES",         "RATTATAT",         "GOALKEEPERS",         "FANFORCED",         "ARCHIVES",         "DUMMYRUN",         "RUMBALL",         "BREATHTAKING",         "DETERGENT",         "HORSEDRAWN",         "CURSIVE",         "NOTABLE",         "KNAPSACK",         "AIRHEAD",         "AUTOBAHNS",         "USELESS",         "FUNDAMENTALS",         "ADMISSION",         "BACTERIA",         "BROUHAHA",         "ORDEAL",         "POSTDATED",         "CONTOURS",         "FLIPFLOPS",         "DISCOURSES",         "FREEWHEELER",         "ENTRAILS",         "MASTICATION",         "OPAL",         "OFFGUARD",         "DELVES",         "TENTATIVE",         "WHOLESOME",         "PIEBALD",         "OUTGOING",         "MUTATIONS",         "PACIFIST",         "PRINCIPALITY",         "KEYRINGS",         "SHARECROPPERS",         "BEDROCKS",         "HOOT",         "DENIGRATE",         "INVERTEBRATE",         "SHORTBREAD",         "FLEETFOOTED",         "WRONGFOOTED",         "MUMMIFIED",         "TOPNOTCHER",         "IDEALISTIC",         "FASTFOOD",         "FARFETCHED",         "COUPE",         "ANTIQUATED",         "GRANARY",         "DOUBLEBUNGER",         "OBJECTIVE",         "SUMMIT",         "NIGHTMARE",         "THOROUGHFARE",         "SLIPSTREAM",         "MINDSET",         "TOTTERING",         "EMBARGO",         "LEMONCELLO",         "GRAVITAS",         "CATAPULT",         "CARGOES",         "QUADRANT",         "SHOTGUN",         "BLOCKBUSTER",         "ADDENDUM", 
"FREEZEFRAME",         "BIOLOGICAL",         "STOCKEXCHANGE",         "ACCENTS",         "SUSPENDERS",         "ECHOCHAMBER",         "TEMPLATES",         "CHEAPSKATE",         "SUNBEAMS",         "TOASTMASTER",         "WISECRACKERS",         "SIGNWRITER",         "PUMPKIN",         "HAIRRAISING",         "BROADBAND",         "FACEBOOK",         "STILTON",         "JUDGES",         "SHARPSHOOTER",         "LAWSUIT",         "SUPREMIST",         "COWPAT",         "MUMBOJUMBO",         "REPOSSESSING",         "GULLIBLE",         "HASHTAG",         "CANDELABRA",         "OPPORTUNIST",         "PROPAGANDA",         "CLIPBOARD",         "NIGHTCAP",         "LAURELS",         "DESSICATED",         "OFFKEY",         "LIGHTYEAR",         "ALIENATE",         "AMPHIBIAN",         "DISINCLINED",         "SHAMROCK",         "SWEEPSTAKES",         "TIMETABLE",         "ITINERANT",         "PREMIERSHIP",         "MOCKORANGE",         "GUNSHY",         "SINGLEMINDED",         "DRIFTWOOD",         "FRETWORK",         "TERMINUS",         "PARAMOUNT",         "ASSAILANTS",         "ROADWORTHY",         "MUSHROOM",         "LOWBROW",         "DRAFTDODGER",         "PORTERHOUSE",         "GNATS",         "DASHBOARD",         "NONPLUSSED",         "CUSTODIAN",         "INTUITION",         "ANGLEGRINDER",         "TENNANTS",         "WEBSITE",         "FIGUREHEAD",         "HEDGEHOGS",         "CLOGDANCING",         "RACECALLERS",         "HANDICRAFT",         "DRESSMAKING",         "ILLADVISED",         "MONUMENTAL",         "CANTEEN",         "IRREVERSIBLE",         "WINDCHEATER",         "BUNGALOW",         "INNOCENTS",         "PESTLE",         "HOGWASH",         "HABITAT",         "DREADLOCKS",         "BULLHEADED",         "ELASTICITY",         "CENTIGRADE",         "SWEATBAND",         "POPSICLE",         "STEREOTYPE",         "STUDYING",         "PLAID",         "FLAGPOLE",         "WARRANTED",         "WINEPRESS",         "SHORTHANDED",         "PUFFIN",         "BINGO",         "HINTERLAND",         "DEBRIEF",         "COUNTERTENOR",         "METRONOME",         "EMULSION", 
"EIDERDOWN",         "COUNTERFEIT",         "ABASEMENT",         "ALASKA",         "AIRFRYER",         "MANAGED",         "FORTIFIED",         "FETED",         "NEGATIVITY",         "DENSITY",         "COOPERATIVE",         "HORSEPLAY",         "PARTICIPANTS",         "IMMOBILITY",         "CATNAP",         "WEDDINGRING",         "DEPTHCHARGE",         "BLINDFOLD",         "OUTSTANDING",         "BANNERS",         "PITTERPATTER",         "LIKEWISE",         "JUST",         "NEIGHBOURS",         "MANGROVE",         "PORT",         "GAPTEETH",         "QUAIL",         "DROMEDARIES",         "BEESTING",         "DAYBREAK",         "NOSEJOB",         "BOOKMAKERS",         "AFFIRMATIONS",         "MADHATTER",         "REARVISION",         "DUMBFOUNDED",         "BULLFIGHTER",         "RAFTERS",         "MINESHAFT",         "EXCLAIM",         "DEFECTIVE",         "BELOVED",         "MALLEABLE",         "EXACT",         "WARDROBE",         "LONESOME",         "FRAMEWORK",         "FOOTFAULTS",         "BILINGUAL", 
"CRUMBBUM",         "DEADBEAT",         "DICEY",         "GRANITE",         "LBW",         "SEANCE",         "BEAMBALANCE",         "RAMPAGE",         "STYMIED",         "SNOWBALL",         "FERRARI",         "SWALLOW",         "EXAMPLE",         "PASSERBY",         "WILLYNILLY",         "PUPILS",         "RUSTIC",         "UNDERWEAR",         "CIRCULATING",         "TAMER",         "PRIMEMOVER",         "WORDPLAY",         "ARTICLED",         "GOULASH",         "MUSHROOM",         "PLAINSAILING",         "LOVEMATCH",         "PIPEDREAM",         "DISTILLERY",         "PITHHELMET",         "OR",         "CHEERIO",         "ALTERNATORS",         "FINGERTIPS",         "JETTISON",         "PERPETUAL",         "REMOVALIST",         "COMMENTATOR",         "MINDLESS",         "LACKADAY",         "CUSTOMMADE",         "OSOPHICAL",         "BOOKKEEPING",         "GUNSLINGERS",         "ELEMENTARY",         "BOOKWORM",         "TSHIRT",         "GENTRY",         "LEASTWISE",         "UNGAINLY", 
"HALFBAKED",         "PAYDIRT",         "PETRIFIED",         "ENDEAR",         "PLUTOCRAT",         "LEVELHEADED",         "KINGFISHER",         "SHOWSTOPPER",         "TOWNSHIP",         "TRICKLE",         "CHIPPER",         "COURTIERS",         "AUTOPSY",         "OLDHAT",         "PLUNGER",         "INFORMANTS",         "AUTOPEN",         "ESCAPIST",         "LIGHTHEADED",         "PROFUSION",         "INABILITY",         "MONOGRAM",         "STOVEPIPES",         "ELATED",         "ATTRIBUTE", 
"HANDLEBARS",         "SOLVENCY",         "SINGLETS",         "MICROSCOPE",         "SNAGGLE",         "FREELOADER",         "LICENTIOUS",         "VETOES",         "FORBIDDING",         "JAPE",         "JERKY",         "CRASHCOURSES",         "CHEATSHEETS",         "RAPIDFIRE",         "ROCKABILLY",         "QUANTUMLEAP",         "DATA",         "PEANUT",         "EQUIP",         "REWARD",         "CRANKSHAFT",         "WOODWIND",         "BOOKLET",         "COWER",         "BUTTERFLY",         "BOWER",         "WIGGLEROOM",         "PRESENTABLE",         "MILLENIUM",         "CROSSWORDS",         "CRESTFALLEN",         "RANKLED",         "BLOODSHED",         "ODDLOTS",         "DECRY",         "GROUNDLESS",         "FLUKES",         "GREENERGRASS",         "HUSHPUPPIES",         "SINGALONG",         "CHOCKABLOCK",         "BLAMELESS",         "PITCHPERFECT",         "SUMMER",         "SATIRE",         "PENDULUM",         "OUTOFBOUNDS",         "THINKTANK",         "FOOTPRINTS",         "SNAPDRAGON",         "SITCOMS",         "ATTENDANCES",         "FLYBYNIGHTER",         "CONFUSED",         "MAKESHIFT",         "CRUSHED",         "LIONISED",         "RISIBLE",         "BEARBAITING",         "ROUNDROBIN",         "PERMACULTURE",         "GROUNDSWELL",         "CRITERIA",         "MURMUR",         "SHIPSHAPE",         "BUTTONS",         "REDDISH",         "PALETTE",         "ARRIVALS",         "PIGOUT",         "ERASURE",         "BRISTLING",         "TRASHTALKING",         "BIRDBRAINED",         "XYLOPHONE", 
"GIGECONOMY",         "PAUPER",         "FALLGUYS",         "FATTEN",         "HUBBUB",         "NAPKIN",         "PANTALOONS",         "TOILETROLL",         "MISGIVINGS",         "OUTOFSORTS",         "BABYGRAND",         "FAIRMINDED",         "HOPSCOTCH",         "BONELAZY",         "UNHINGED",         "DEPARTMENTAL",         "BITPLAYER",         "DETESTS",         "EVERGREEN",         "BANKCARD",         "DECK",         "PILLBOX",         "REPULSED",         "SILVERFISH",         "UNBEARABLE",         "TROMBONE",         "HORSDECOMBAT",         "GENES",         "SUPERVISOR",         "GUESSWORK",         "AGAIN",         "SIDEWINDER",         "ENTOURAGE",         "LUMBERJACK",         "COMBATANT",         "ESCHEW",         "AKIMBO",         "SOLETRADER",         "SERVICEABLE",         "AVANTGARDE",         "FALSEDAWN",         "OUTRIGHT",         "SEAFARING",         "INOPERABLE",         "NUGGETY",         "CARBUNCLE",         "TRUANCY",         "QUIZZICAL",         "KITTY",         "JOINTVENTURE", 
 "HEATWAVE",         "SUPERNATURAL",         "OFFSPRING",         "SKATEBOARD",         "COREVALUES",         "IMMATERIAL",         "MISERYGUTS",         "ENRAPTURED",         "FITTER",         "DEADHEATS",         "UPPERSET",         "TOUCAN",         "DAYS",         "DOUBLEFAULT",         "LISTLESS",         "INSTINCT",         "BESPOKE",         "SPACECRAFT",         "YARDAGE",         "SPELLBOUND",         "HARDDRIVE",         "DISPENSARY",         "FRENCHTOAST",         "EXPRESSWISH",         "WAGONWHEELS",         "UNICORN",         "TWINSET",         "SEACHANGE",         "HOBBYHORSE",         "MILES",         "POLESAPART",         "FITFUL",         "OUCH",         "MILKYWAY",         "COWL",         "CRASHDUMMIES",         "BRAINDRAIN",         "JUBILATION",         "SANDSTONE",         "BIRDBRAINED",         "GREYHOUND",         "IRRESOLUTE",         "REPUDIATE",         "PLAYFULLY",         "ABSTAINING",         "PORPOISE",         "OPINE",         "RECORDER",         "GOAT",         "PHONIES", 
"DERIDED",         "URN",         "HIDEBOUND",         "SKELETON",         "PHONETICS",         "SPECULATING",         "TICKETYBOO",         "DRAWCARD",         "SEAWORTHY",         "PENTATHLON",         "FLIGHTPATHS",         "REPAST",         "LEGACY",         "ALPHABETICAL",         "BULLDOZER",         "NOTABLES",         "BILLFOLD",         "POLYGON",         "FLEAS",         "SINGLEMINDED",         "STRETCHERED",         "FINGERFOOD",         "UNDERCOVER",         "SNICKER",         "SIDEISSUE",         "SHORTSTOP",         "PREFERENCES",         "HOTDOGS",         "HATCHBACK",         "TEMPERATE",         "BAKINGSODA",         "PARACHUTIST",         "IMPECCABLE",         "OPENCUT",         "NOVICE",         "SWISS",         "AUTONOMY",         "COUNTEROFFER",         "CHARGER",         "DOPPELGANGER",         "COLT",         "BULKBILLING",         "JUMBOJET",         "OUTCASTS",         "PENTHOUSE",         "MINEHOST",         "GARBAGE",         "CATEGORICAL",         "TRIPLICATE",         "GLADDEN", 
"GIFTCARD",         "NEWSHOUND",         "ADLIB",         "THUMBNAIL",         "FLAWED",         "IDEALISTIC",         "WEIGHBRIDGE",         "FALLENARCHES",         "AUDIOLOGY",         "PROSPECTUS",         "ADVERSE",         "GOATEE",         "CRUELSUMMER",         "MANIFOLD",         "IMPAIRED",         "BACHELORPAD",         "INDIGNITY",         "ADDITIVE",         "LEAPFROG",         "FLEETING",         "FOREBEARS",         "DEFENCELESS",         "DEPORTMENT",         "POINTBLANK",         "UNDERGROWTH",         "TRAFFICJAM",         "FILLY",         "FURTIVE",         "MOUSSE",         "FARSIGHTED",         "FRESHFACED",         "CONTENTED",         "OVERHEADS",         "UNASSUMING",         "BIGBUCKS",         "ILLGOTTEN",         "CONSORTIUM",         "HOME",         "MONKEYWRENCH",         "BUNUNDRUM",         "ANGEL",         "UNIVERSAL",         "NONDESCRIPT",         "NOVICE",         "HISTRIONICS",         "HOTDIGGITY",         "CUBICLE",         "CROSSROADS",         "TAPDANCING",         "CATASTROPHE", 
"DEPARTMENT",         "FLEECED",         "OUTSPOKEN",         "HICCUP",         "FURROWS",         "SEASHANTY",         "GERTRUDIS",         "AMENABLE",         "DEWDROP",         "EXTRA",         "RANKORDER",         "MARSBAR",         "SHYSTERS",         "VISIONARIES",         "SAGO",         "DETRACTOR",         "SPREADSHEETS",         "PLAYMATES",         "PIGHEADED",         "BELLRINGING",         "RUDIMENTARY",         "SKILIFT",         "AIRY",         "SATIRES",         "STOOL",         "MOBILEPHONE",         "INDIANRUBBER",         "MOLLIFY",         "CASHSTRAPP